# Setup
title: 'LIS-570-Research-Assesment-And-Design'
url: https://nniiicc.github.io/LIS-570-Au2021

# Settings
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
highlighter: rouge
permalink: /:title/
future: true
# safe: true # breaks local rendering if enabled
timezone: America/New_York
analytics:
  tracking_id:

collections:
  '2019':
    output: true
  '2020':
    output: true

# Excludes
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - vendor
